export const usStateNames = [
  { key: 'AK', value: 'AK', title: 'Alaska' },
  { key: 'AL', value: 'AL', title: 'Alabama' },
  { key: 'AR', value: 'AR', title: 'Arkansas' },
  { key: 'AZ', value: 'AZ', title: 'Arizona' },
  { key: 'CA', value: 'CA', title: 'California' },
  { key: 'CO', value: 'CO', title: 'Colorado' },
  { key: 'CT', value: 'CT', title: 'Connecticut' },
  { key: 'DE', value: 'DE', title: 'Delaware' },
  { key: 'FL', value: 'FL', title: 'Florida' },
  { key: 'GA', value: 'GA', title: 'Georgia' },
  { key: 'HI', value: 'HI', title: 'Hawaii' },
  { key: 'IA', value: 'IA', title: 'Iowa' },
  { key: 'ID', value: 'ID', title: 'Idaho' },
  { key: 'IL', value: 'IL', title: 'Illinois' },
  { key: 'IN', value: 'IN', title: 'Indiana' },
  { key: 'KS', value: 'KS', title: 'Kansas' },
  { key: 'KY', value: 'KY', title: 'Kentucky' },
  { key: 'LA', value: 'LA', title: 'Louisiana' },
  { key: 'MA', value: 'MA', title: 'Massachusetts' },
  { key: 'MD', value: 'MD', title: 'Maryland' },
  { key: 'ME', value: 'ME', title: 'Maine' },
  { key: 'MI', value: 'MI', title: 'Michigan' },
  { key: 'MN', value: 'MN', title: 'Minnesota' },
  { key: 'MO', value: 'MO', title: 'Missouri' },
  { key: 'MS', value: 'MS', title: 'Mississippi' },
  { key: 'MT', value: 'MT', title: 'Montana' },
  { key: 'NC', value: 'NC', title: 'North Carolina' },
  { key: 'ND', value: 'ND', title: 'North Dakota' },
  { key: 'NE', value: 'NE', title: 'Nebraska' },
  { key: 'NH', value: 'NH', title: 'New Hampshire' },
  { key: 'NJ', value: 'NJ', title: 'New Jersey' },
  { key: 'NM', value: 'NM', title: 'New Mexico' },
  { key: 'NV', value: 'NV', title: 'Nevada' },
  { key: 'NY', value: 'NY', title: 'New York' },
  { key: 'OH', value: 'OH', title: 'Ohio' },
  { key: 'OK', value: 'OK', title: 'Oklahoma' },
  { key: 'OR', value: 'OR', title: 'Oregon' },
  { key: 'PA', value: 'PA', title: 'Pennsylvania' },
  { key: 'RI', value: 'RI', title: 'Rhode Island' },
  { key: 'SC', value: 'SC', title: 'South Carolina' },
  { key: 'SD', value: 'SD', title: 'South Dakota' },
  { key: 'TN', value: 'TN', title: 'Tennessee' },
  { key: 'TX', value: 'TX', title: 'Texas' },
  { key: 'UT', value: 'UT', title: 'Utah' },
  { key: 'VA', value: 'VA', title: 'Virginia' },
  { key: 'VT', value: 'VT', title: 'Vermont' },
  { key: 'WA', value: 'WA', title: 'Washington' },
  { key: 'WI', value: 'WI', title: 'Wisconsin' },
  { key: 'WV', value: 'WV', title: 'West Virginia' },
  { key: 'WY', value: 'WY', title: 'Wyoming' }
]
